apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-html-app
  template:
    metadata:
      labels:
        app: my-html-app
    spec:
      containers:
      - name: my-html-app
        image: my-profile    # This is the Docker image we built locally
        imagePullPolicy: Never # Tells Kubernetes not to pull from a registry
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-html-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: my-html-app